"""`ctx init`: the bootstrap interview that produces a corpus's L1 profile.

`run_interview(layout, answers=None)` writes `core/profile.md` -- the
user-tailoring layer every session force-loads. Two modes, one code path
for the actual write:

- **Non-interactive** (`answers` is a `dict`): used by scripted/CI
  scaffolding and by the test suite. Writes (or overwrites) the profile
  directly from the given answers -- no prompts, no confirmation. Calling
  it twice is idempotent in the practical sense that matters here: same
  answers in -> byte-identical file out, and a *different* answers dict
  replaces the file's content rather than appending to it. There is never
  more than one `core/profile.md`.
- **Interactive** (`answers=None`): prompts on stdin for each field in
  `ANSWER_FIELDS`. If a customized profile already exists (anything other
  than the scaffold's `PROFILE_PLACEHOLDER`), asks for confirmation first
  rather than silently clobbering a human's prior answers -- "offers to
  revise rather than duplicate". A Ctrl-C anywhere in this path is caught
  and exits cleanly (prints a cancellation notice, leaves any existing
  file untouched) rather than printing a traceback.

Answer dict keys -- the only ones `run_interview` reads; extra keys are
ignored, missing keys render as `UNSPECIFIED_ANSWER`:

    name                       -- the user's name
    working_style              -- how they like to work (pace, autonomy, review)
    communication_preferences  -- tone/directness/verbosity preferences
    domain_purpose             -- what this corpus's domain/purpose is

Deliberately out of scope for this module (build-ladder: minimum that
works): the interactive revise path does not pre-fill prompts with the
profile's *current* values -- it re-asks all four questions fresh. Reading
prior answers back out of the rendered markdown would need a parser this
module has no other use for; revisit if a later module wants round-trip
editing.
"""

from __future__ import annotations

from pathlib import Path

from ctx_core.layout import PROFILE_PLACEHOLDER, Layout

# --- answer schema: (key, section heading, interactive prompt text) ---
# The single source of truth for the answer-dict keys, the profile's
# section headings, and the interactive question wording -- keeps the
# three in lockstep instead of duplicating the key list three times.
ANSWER_FIELDS: tuple[tuple[str, str, str], ...] = (
    ("name", "Name", "Your name: "),
    (
        "working_style",
        "Working style",
        "How do you like to work (pace, autonomy, review style)?: ",
    ),
    (
        "communication_preferences",
        "Communication preferences",
        "Communication preferences (tone, directness, verbosity)?: ",
    ),
    (
        "domain_purpose",
        "Domain purpose",
        "What is this corpus's domain or purpose?: ",
    ),
)

# Rendered in place of any answer that's missing or blank after stripping.
UNSPECIFIED_ANSWER = "(not specified)"

# Header/intro lines for the generated profile.md.
PROFILE_TITLE = "# Profile"
PROFILE_INTRO = "Generated by `ctx init`. Edit this file freely -- it is yours."

# Interactive-mode prompts and messages.
REVISE_PROMPT = "A profile already exists here. Revise it? [y/N]: "
CANCELLED_MESSAGE = "\nInterview cancelled; profile.md left unchanged."
YES_ANSWERS = frozenset({"y", "yes"})


def run_interview(layout: Layout, answers: dict[str, str] | None = None) -> None:
    """Write `core/profile.md` for the corpus at `layout`.

    `answers=None` drives an interactive prompt loop over stdin. A supplied
    `dict` skips the loop entirely and writes directly -- this is the path
    the test suite and any scripted/CI scaffolding drive.
    """
    if answers is not None:
        _write_profile(layout, answers)
        return

    profile_path = layout.core / "profile.md"
    try:
        if _is_customized(profile_path):
            if not _ask_yes_no(REVISE_PROMPT, default=False):
                return
        collected = _prompt_answers()
    except KeyboardInterrupt:
        print(CANCELLED_MESSAGE)
        return

    _write_profile(layout, collected)


def _is_customized(profile_path: Path) -> bool:
    """True iff `profile_path` exists and is not the shipped placeholder."""
    if not profile_path.is_file():
        return False
    return profile_path.read_text(encoding="utf-8") != PROFILE_PLACEHOLDER


def _ask_yes_no(prompt: str, *, default: bool) -> bool:
    reply = input(prompt).strip().lower()
    if not reply:
        return default
    return reply in YES_ANSWERS


def _prompt_answers() -> dict[str, str]:
    answers: dict[str, str] = {}
    for key, _heading, prompt in ANSWER_FIELDS:
        answers[key] = input(prompt).strip()
    return answers


def _render_profile(answers: dict[str, str]) -> str:
    lines: list[str] = [PROFILE_TITLE, "", PROFILE_INTRO]
    for key, heading, _prompt in ANSWER_FIELDS:
        value = str(answers.get(key, "")).strip() or UNSPECIFIED_ANSWER
        lines.append("")
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(value)
    lines.append("")
    return "\n".join(lines)


def _write_profile(layout: Layout, answers: dict[str, str]) -> None:
    layout.core.mkdir(parents=True, exist_ok=True)
    content = _render_profile(answers)
    (layout.core / "profile.md").write_text(content, encoding="utf-8", newline="\n")
